name: Auto-merge Feature → Demo

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'


jobs:
  merge-into-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}


      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Trazer branches
        run: |
          git fetch origin demo

      - name: Fazer merge e push para demo
        run: |
          git checkout demo
          set +e
          git merge --no-ff ${{ github.ref_name }} -m "chore: auto-merge ${{ github.ref_name }} → demo"
          status=$?
          set -e
          if [ $status -ne 0 ]; then
            echo "❌ Merge conflict detected. Please resolve manually."
            git merge --abort
            exit 1
          fi
          git push origin demo
